name: Deploy to EC2 (Production)

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Configure the SSH key for EC2 connection
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY_PROD }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Add IPs from the comma-separated list
          for host in $(echo "${{ secrets.HOST_DNS_PROD }}" | tr "," "\n"); do
            ssh-keyscan -H $host >> ~/.ssh/known_hosts
          done

      # Step 3: Iterate over instances and deploy
      - name: Deploy to EC2 instances
        run: |
          for host in $(echo "${{ secrets.HOST_DNS_PROD }}" | tr "," "\n"); do
            ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@$host << 'EOF'
              # Install git if it's not already installed
              sudo yum install -y git
              
              # Navigate to the target directory or clone the repository
              cd ${{ secrets.TARGET_DIR }} || git clone https://github.com/AlexandraN2001/loadbalancer.git
              cd loadbalancer
              
              # Pull latest changes from the 'qa' branch
              git pull origin qa
              
              # Copy index.html to the nginx directory
              sudo cp index.html /usr/share/nginx/html/
              
              # Restart nginx service to apply the changes
              sudo systemctl restart nginx
            EOF
          done
