name: Deploy to EC2 Instances

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        instance:
          - { name: "Instance 1", host: ${{ secrets.HOST_DNS }}, ssh_key: ${{ secrets.EC2_SSH_KEY }} }
          - { name: "Instance 2", host: ${{ secrets.HOST2_DNS }}, ssh_key: ${{ secrets.EC2_SSH_KEY_2 }} }

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Deploy to ${{ matrix.instance.name }}
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ matrix.instance.ssh_key }}
        REMOTE_HOST: ${{ matrix.instance.host }}
        REMOTE_USER: ${{ secrets.EC2_USER }}
        TARGET: ${{ secrets.TARGET_DIR }}

    - name: Executing remote ssh commands on ${{ matrix.instance.name }}
      uses: appleboy/ssh-action@master
      with:
        host: ${{ matrix.instance.host }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ matrix.instance.ssh_key }}
        script: |
          cd webSite2
          git pull origin main
          sudo mv index.html /var/www/html/
