name: Deploy to EC2 Instances

on:
  push:
    branches:
      - main

jobs:
  deploy_instance_1:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Deploy to Instance 1
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.HOST_DNS }}
        REMOTE_USER: ${{ secrets.EC2_USER }}
        TARGET: ${{ secrets.TARGET_DIR }}

    - name: Ejecutando comandos remotos via SSH en Instance 1
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd webSite2
          git pull origin main
          sudo mv index.html /var/www/html/

  deploy_instance_2:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Deploy to Instance 2
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY_2 }}
        REMOTE_HOST: ${{ secrets.HOST2_DNS }}
        REMOTE_USER: ${{ secrets.EC2_USER }}
        TARGET: ${{ secrets.TARGET_DIR }}

    - name: Ejecutando comandos remotos via SSH en Instance 2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST2_DNS }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY_2 }}
        script: |
          cd webSite2
          git pull origin main
          sudo mv index.html /var/www/html/
