name: Deploy to EC2 (Desarrollo)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Hacer checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v2

      # Paso 2: Configurar la clave SSH para conectar con las instancias EC2
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY_PROD }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ec2-3-94-248-188.compute-1.amazonaws.com >> ~/.ssh/known_hosts
          ssh-keyscan -H ec2-54-146-243-56.compute-1.amazonaws.com >> ~/.ssh/known_hosts
          ssh-keyscan -H ec2-44-221-168-140.compute-1.amazonaws.com >> ~/.ssh/known_hosts
          ssh-keyscan -H ec2-98-85-158-95.compute-1.amazonaws.com >> ~/.ssh/known_hosts


      # Paso 3: Desplegar en las instancias de desarrollo
      - name: Deploy 1
        run: |
          ssh -o StrictHostKeyChecking=no -i "${{ secrets.EC2_SSH_KEY_PROD_1 }}" ec2-3-94-248-188.compute-1.amazonaws.com << 'EOF'
            cd /home/ec2-user/loadbalancer || git clone https://github.com/AlexandraN2001/loadbalancer.git
            cd loadbalancer
            git pull origin main
            sudo cp index.html /var/www/html/
            sudo chown -R ec2-user:ec2-user /var/www/html
            sudo chmod -R 755 /var/www/html
            sudo systemctl restart nginx
          EOF

      - name: Deploy 2
        run: |
          ssh -o StrictHostKeyChecking=no -i "${{ secrets.EC2_SSH_KEY_PROD_2}}" ec2-54-146-243-56.compute-1.amazonaws.com << 'EOF'
            cd /home/ec2-user/loadbalancer || git clone https://github.com/AlexandraN2001/loadbalancer.git
            cd loadbalancer
            git pull origin main
            sudo cp index.html /var/www/html/
            sudo chown -R ec2-user:ec2-user /var/www/html
            sudo chmod -R 755 /var/www/html
            sudo systemctl restart nginx
          EOF

      # Paso 4: Desplegar en las instancias de producción
      - name: Deploy 3
        run: |
          ssh -o StrictHostKeyChecking=no -i "${{ secrets.EC2_SSH_KEY_PROD_3 }}" ec2-44-221-168-140.compute-1.amazonaws.com << 'EOF'
            cd /home/ec2-user/loadbalancer || git clone https://github.com/AlexandraN2001/loadbalancer.git
            cd loadbalancer
            git pull origin main
            sudo cp index.html /var/www/html/
            sudo chown -R ec2-user:ec2-user /var/www/html
            sudo chmod -R 755 /var/www/html
            sudo systemctl restart nginx
          EOF

      - name: Deploy 4
        run: |
          ssh -o StrictHostKeyChecking=no -i "${{ secrets.EC2_SSH_KEY_PROD_4 }}" ec2-98-85-158-95.compute-1.amazonaws.com << 'EOF'
            cd /home/ec2-user/loadbalancer || git clone https://github.com/AlexandraN2001/loadbalancer.git
            cd loadbalancer
            git pull origin main
            sudo cp index.html /var/www/html/
            sudo chown -R ec2-user:ec2-user /var/www/html
            sudo chmod -R 755 /var/www/html
            sudo systemctl restart nginx
          EOF
