name: Deploy to EC2 (Production)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Configure the SSH key to connect to the EC2 instances
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY_PROD }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          for host in $(echo "${{ secrets.HOST_DNS_PROD }}" | tr "," "\n"); do
            ssh-keyscan -H $host >> ~/.ssh/known_hosts
          done

      # Step 3: Deploy to EC2 instances
      - name: Deploy to EC2 instances
        run: |
          for host in $(echo "${{ secrets.HOST_DNS_PROD }}" | tr "," "\n"); do
            ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@$host << 'EOF'
              # Clone the repository if it doesn't exist
              cd ${{ secrets.TARGET_DIR }} || git clone https://github.com/AlexandraN2001/loadbalancer.git ${{ secrets.TARGET_DIR }}
              cd ${{ secrets.TARGET_DIR }}
              
              # Pull the latest changes from the main branch
              git pull origin main

              # Copy index.html to nginx's default directory
              sudo cp index.html /usr/share/nginx/html/

              # Restart nginx to apply the changes
              sudo systemctl restart nginx
            EOF
          done
