name: Deploy to EC2 (QA)

on:
  push:
    branches:
      - qa

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up the SSH key for connecting to the EC2 instances
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY_QA }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Add instance hostnames to known_hosts
          for host in $(echo "${{ secrets.HOST_DNS_QA }}" | tr "," "\n"); do
            ssh-keyscan -H $host >> ~/.ssh/known_hosts
          done

      # Step 3: Deploy to each QA instance
      - name: Deploy to QA Instances
        run: |
          for host in $(echo "${{ secrets.HOST_DNS_QA }}" | tr "," "\n"); do
            ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@$host << 'EOF'
              # Check and install required packages
              if ! command -v git &> /dev/null; then
                sudo dnf install -y git
              fi
              if ! command -v nginx &> /dev/null; then
                sudo dnf install -y nginx
              fi

              # Ensure nginx is running and enabled
              sudo systemctl start nginx
              sudo systemctl enable nginx

              # Create target directory if it doesn't exist
              mkdir -p ${{ secrets.TARGET_DIR }}

              # Navigate to the target directory or clone the repository
              if [ ! -d "${{ secrets.TARGET_DIR }}/loadbalancer" ]; then
                git clone https://github.com/AlexandraN2001/loadbalancer.git ${{ secrets.TARGET_DIR }}/loadbalancer
              fi
              cd ${{ secrets.TARGET_DIR }}/loadbalancer

              # Pull latest changes from the 'qa' branch
              git fetch origin qa
              git reset --hard origin/qa

              # Deploy the index.html to nginx's web root
              sudo cp index.html /usr/share/nginx/html/

              # Restart nginx to apply changes
              sudo systemctl restart nginx
            EOF
          done
