name: Deploy to EC2 (QA)

on:
  push:
    branches:
      - qa

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Configure the SSH key for EC2 connection
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY_QA }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Add IPs from the comma-separated list
          for host in $(echo "${{ secrets.HOST_DNS_QA }}" | tr "," "\n"); do
            ssh-keyscan -H $host >> ~/.ssh/known_hosts
          done

      # Step 3: Iterate over instances and deploy
      - name: Deploy to EC2 instances
        run: |
          for host in $(echo "${{ secrets.HOST_DNS_QA }}" | tr "," "\n"); do
            ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@$host << 'EOF'
              sudo yum install -y git
              cd ${{ secrets.TARGET_DIR }} || git clone https://github.com/AlexandraN2001/loadbalancer.git
              cd loadbalancer
              git pull origin qa         
              sudo cp index.html /usr/share/nginx/html/
              sudo systemctl restart nginx
            EOF
          done
